mailgun:
  api_key: "" # LEAVE BLANK IF USING GITHUB ACTIONS / ENV SECRETS
  domain: ""
  from: ""
  to:
    - ""


whois:
  api_key: "" # LEAVE BLANK IF USING GITHUB ACTIONS / ENV SECRETS


domains:
  - ""
